In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
#버전 2.0으로 업그레이드됨에 따라 v1과 호환이 되지 않음

Instructions for updating:
non-resource variables are not supported in the long term


In [0]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [0]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

정상모델

In [0]:
 def checkLearningRate(input_learning_rate):
  hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

  # Cross entropy cost/loss
  cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
  # Try to change learning_rate to small numbers
  optimizer = tf.train.GradientDescentOptimizer(learning_rate=input_learning_rate).minimize(cost)

  # Correct prediction Test model
  prediction = tf.argmax(hypothesis, 1)
  is_correct = tf.equal(prediction, tf.argmax(Y, 1))
  accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

  # Launch graph
  with tf.Session() as sess:
      # Initialize TensorFlow variables
      sess.run(tf.global_variables_initializer())

      for step in range(201):
          cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
          print(step, cost_val, W_val)

      # 기존의 학습은 x_data, y_data로 진행하고, 실제 시행은 test 데이터를 이용함
      # predict
      print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
      # Calculate the accuracy
      
      print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

In [15]:
checkLearningRate(0.1)

0 1.4198247 [[-2.3365529   0.07888246 -0.6625023 ]
 [-0.45158696 -1.2234552   0.3632071 ]
 [ 0.25930756 -0.1430094  -1.234821  ]]
1 1.1899104 [[-2.3412132   0.07492074 -0.6538801 ]
 [-0.46134475 -1.1723537   0.32186347]
 [ 0.24964853 -0.10738011 -1.2607912 ]]
2 1.1458895 [[-2.3438244   0.0634444  -0.63979256]
 [-0.4628035  -1.1558927   0.3068612 ]
 [ 0.2507421  -0.1055363  -1.2637286 ]]
3 1.1348133 [[-2.346228    0.05076076 -0.62470543]
 [-0.4634489  -1.1457412   0.29735515]
 [ 0.25302535 -0.10960792 -1.2619402 ]]
4 1.124787 [[-2.3487556   0.03810522 -0.6095222 ]
 [-0.46474743 -1.1359797   0.2888921 ]
 [ 0.2546642  -0.11393705 -1.2592499 ]]
5 1.1149045 [[-2.3512795   0.02552016 -0.59441316]
 [-0.46590763 -1.1264571   0.28052968]
 [ 0.25636864 -0.11842363 -1.2564678 ]]
6 1.1051478 [[-2.353825    0.01304435 -0.5793918 ]
 [-0.46706453 -1.1169835   0.27221304]
 [ 0.25799793 -0.12287875 -1.253642  ]]
7 1.0955164 [[-2.3563838e+00  6.7402906e-04 -5.6446272e-01]
 [-4.6816745e-01 -1.1075826e+00

과다학습 (learning rate = 1.5로 잡아본 경우

In [16]:
checkLearningRate(1.5)

0 7.9492126 [[-0.58687407  0.64067554 -0.04799063]
 [-3.1998131   1.1527097   0.24765311]
 [-1.960205    0.9916997   1.2069293 ]]
1 14.226137 [[-0.21187407 -0.23986757  0.4575525 ]
 [-0.7623131  -2.6414595   1.604322  ]
 [ 0.47729504 -2.5467849   2.3079138 ]]
2 24.95903 [[ 0.16312057  0.32263237 -0.47994205]
 [ 1.6751761  -0.01645947 -3.458167  ]
 [ 2.9147897   0.26571512 -2.942081  ]]
3 16.7257 [[-0.95584285  0.8790959   0.0825579 ]
 [-2.4376702   2.596387   -1.9581672 ]
 [-1.204092    3.0720963  -1.6295811 ]]
4 25.7822 [[-5.8084285e-01 -5.8404088e-02  6.4505786e-01]
 [-1.7040968e-04 -1.3411131e+00 -4.5816728e-01]
 [ 1.2334077e+00 -6.7790365e-01 -3.1708118e-01]]
5 5.079342 [[-1.3919349   0.49950367  0.8982421 ]
 [-3.3575268   1.2739037   0.28417224]
 [-2.3904355   2.129021    0.49983716]]
6 18.412102 [[-1.0169349  -0.42305356  1.4457994 ]
 [-0.9200268  -2.6325853   1.7531612 ]
 [ 0.04706454 -1.6047385   1.7960963 ]]
7 24.618769 [[-0.641935    0.13944644  0.50829947]
 [ 1.517473   -0.0

local minimum ) learning_rate = 1e-10

In [17]:
checkLearningRate(1e-10)

0 3.7212594 [[ 0.51234764 -1.0354273  -0.9709795 ]
 [ 0.8081775   0.19080248  0.89681035]
 [ 0.4938703   1.9182794  -1.5425318 ]]
1 3.7212594 [[ 0.51234764 -1.0354273  -0.9709795 ]
 [ 0.8081775   0.19080248  0.89681035]
 [ 0.4938703   1.9182794  -1.5425318 ]]
2 3.7212594 [[ 0.51234764 -1.0354273  -0.9709795 ]
 [ 0.8081775   0.19080248  0.89681035]
 [ 0.4938703   1.9182794  -1.5425318 ]]
3 3.7212594 [[ 0.51234764 -1.0354273  -0.9709795 ]
 [ 0.8081775   0.19080248  0.89681035]
 [ 0.4938703   1.9182794  -1.5425318 ]]
4 3.7212594 [[ 0.51234764 -1.0354273  -0.9709795 ]
 [ 0.8081775   0.19080248  0.89681035]
 [ 0.4938703   1.9182794  -1.5425318 ]]
5 3.7212594 [[ 0.51234764 -1.0354273  -0.9709795 ]
 [ 0.8081775   0.19080248  0.89681035]
 [ 0.4938703   1.9182794  -1.5425318 ]]
6 3.7212594 [[ 0.51234764 -1.0354273  -0.9709795 ]
 [ 0.8081775   0.19080248  0.89681035]
 [ 0.4938703   1.9182794  -1.5425318 ]]
7 3.7212594 [[ 0.51234764 -1.0354273  -0.9709795 ]
 [ 0.8081775   0.19080248  0.89681035]
