In [0]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
#버전 2.0으로 업그레이드됨에 따라 v1과 호환이 되지 않음

In [0]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [0]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [21]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  1774918000000.0 
Prediction:
 [[ 940303.6 ]
 [1893021.  ]
 [1489151.9 ]
 [1043861.44]
 [1230261.1 ]
 [1240619.  ]
 [1137062.4 ]
 [1447736.4 ]]
1 Cost:  1.950068e+27 
Prediction:
 [[-3.1149865e+13]
 [-6.2707873e+13]
 [-4.9330023e+13]
 [-3.4580084e+13]
 [-4.0754475e+13]
 [-4.1097498e+13]
 [-3.7667278e+13]
 [-4.7957936e+13]]
2 Cost:  inf 
Prediction:
 [[1.03250426e+21]
 [2.07853691e+21]
 [1.63510995e+21]
 [1.14620340e+21]
 [1.35086203e+21]
 [1.36223193e+21]
 [1.24853264e+21]
 [1.58963035e+21]]
3 Cost:  inf 
Prediction:
 [[-3.4223750e+28]
 [-6.8895917e+28]
 [-5.4197934e+28]
 [-3.7992463e+28]
 [-4.4776147e+28]
 [-4.5153020e+28]
 [-4.1384303e+28]
 [-5.2690446e+28]]
4 Cost:  inf 
Prediction:
 [[1.1343922e+36]
 [2.2836480e+36]
 [1.7964634e+36]
 [1.2593114e+36]
 [1.4841658e+36]
 [1.4966577e+36]
 [1.3717385e+36]
 [1.7464958e+36]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan

In [0]:
#Min-max scale ! Normalized Inputs

In [0]:
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [31]:
xy = MinMaxScaler(xy)
print(xy)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

[[0.9999999  0.9999999  0.         0.9999999  0.9999999 ]
 [0.70548484 0.70439545 0.9999999  0.71881775 0.83755783]
 [0.54412544 0.50274819 0.5760869  0.60646794 0.66063303]
 [0.33890349 0.3136802  0.10869564 0.4598913  0.43800914]
 [0.51435995 0.42582385 0.3043478  0.585048   0.42624397]
 [0.49556174 0.42582385 0.31521736 0.48131129 0.49276132]
 [0.11436063 0.         0.20652172 0.22007774 0.18597236]
 [0.         0.07747099 0.53260864 0.         0.        ]]


In [0]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [33]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  0.34104443 
Prediction:
 [[-0.14326954]
 [ 0.12410635]
 [ 0.16209722]
 [ 0.26688597]
 [ 0.126329  ]
 [ 0.17931387]
 [ 0.36670864]
 [ 0.64311135]]
1 Cost:  0.3410311 
Prediction:
 [[-0.14324689]
 [ 0.1241262 ]
 [ 0.16211355]
 [ 0.26689827]
 [ 0.126344  ]
 [ 0.17932817]
 [ 0.3667168 ]
 [ 0.6431187 ]]
2 Cost:  0.3410179 
Prediction:
 [[-0.1432243 ]
 [ 0.12414601]
 [ 0.16212982]
 [ 0.26691055]
 [ 0.12635905]
 [ 0.17934251]
 [ 0.3667249 ]
 [ 0.64312595]]
3 Cost:  0.3410046 
Prediction:
 [[-0.14320165]
 [ 0.12416577]
 [ 0.16214606]
 [ 0.2669228 ]
 [ 0.126374  ]
 [ 0.17935687]
 [ 0.36673304]
 [ 0.6431333 ]]
4 Cost:  0.34099138 
Prediction:
 [[-0.14317906]
 [ 0.12418562]
 [ 0.16216233]
 [ 0.26693508]
 [ 0.126389  ]
 [ 0.17937115]
 [ 0.36674118]
 [ 0.64314055]]
5 Cost:  0.34097812 
Prediction:
 [[-0.14315641]
 [ 0.12420541]
 [ 0.1621786 ]
 [ 0.2669474 ]
 [ 0.12640405]
 [ 0.17938548]
 [ 0.3667493 ]
 [ 0.6431479 ]]
6 Cost:  0.34096485 
Prediction:
 [[-0.14313382]
 [ 0.12422517]
 [ 0.1621