In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
#버전 2.0으로 업그레이드됨에 따라 v1과 호환이 되지 않음

Instructions for updating:
non-resource variables are not supported in the long term


In [0]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [0]:
X = tf.placeholder("float",[None, 4]) #[N,4]
Y = tf.placeholder("float",[None, 3]) #[N,3]
nb_classes = 3 # 클래스의 갯수를 표현

In [0]:
W = tf.Variable(tf.random_normal([4, nb_classes], name='weight')) # 4개 input(x), output(y) : nb_classes
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')


In [0]:
#tf.nn.softmax = compute softmax activations
#softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

In [0]:
#Cross entropy cost(loss)
cost = tf.reduce_mean(-tf.reduce_sum(Y* tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [19]:
#Launch graph
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

  for step in range(2001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
      print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))
  print('------------------------------------------------------')
  a = sess.run(hypothesis, feed_dict={X: [[1,11 ,7, 9]]})
  print(a, sess.run(tf.arg_max(a,1)))

0 6.3117228
200 0.6232747
400 0.51333666
600 0.42071375
800 0.3308907
1000 0.24615704
1200 0.2159903
1400 0.19712779
1600 0.18120302
1800 0.16758415
2000 0.15581053
------------------------------------------------------
[[8.2930466e-03 9.9169534e-01 1.1541398e-05]] [1]


In [18]:
# Launch graph
# https://github.com/hunkim/DeepLearningZeroToAll/blob/master/lab-06-1-softmax_classifier.py
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
            _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})

            if step % 200 == 0:
                print(step, cost_val)

    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 8.233339
200 0.523849
400 0.43205595
600 0.3567838
800 0.2830611
1000 0.23487589
1200 0.2127719
1400 0.1943693
1600 0.17880522
1800 0.16547453
2000 0.15393421
--------------
[[3.9970833e-03 9.9599481e-01 8.0886384e-06]] [1]
--------------
[[0.8776282  0.11298912 0.00938266]] [0]
--------------
[[1.10872325e-08 3.17533908e-04 9.99682426e-01]] [2]
--------------
[[3.9970833e-03 9.9599481e-01 8.0886384e-06]
 [8.7762809e-01 1.1298921e-01 9.3826689e-03]
 [1.1087233e-08 3.1753362e-04 9.9968243e-01]] [1 0 2]
