In [0]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
#버전 2.0으로 업그레이드됨에 따라 v1과 호환이 되지 않음

Case 1) : basic으로서 코드가 많아지면 스파게티 코드처럼 보임

In [0]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

#목표로 하는 y값
y_data = [152., 185., 180., 196., 142.]

In [0]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [0]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

Case2) Matrix를 이용한 방법

In [0]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b


In [0]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [0]:
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) # 0.0001
train = optimizer.minimize(cost)

In [107]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    #case 1)
    #cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    #Case 2)
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  226972.4 
Prediction:
 [[-271.74323]
 [-323.52905]
 [-320.6745 ]
 [-345.0815 ]
 [-249.48145]]
10 Cost:  8.761099 
Prediction:
 [[149.69254]
 [183.01225]
 [178.4258 ]
 [198.42545]
 [136.88443]]
20 Cost:  6.6745696 
Prediction:
 [[150.96404]
 [184.54749]
 [179.93494]
 [200.06812]
 [138.05779]]
30 Cost:  6.6658325 
Prediction:
 [[150.96425]
 [184.5547 ]
 [179.93852]
 [200.07127]
 [138.06566]]
40 Cost:  6.657154 
Prediction:
 [[150.96066]
 [184.55734]
 [179.93759]
 [200.06952]
 [138.07002]]
50 Cost:  6.648481 
Prediction:
 [[150.95706]
 [184.55994]
 [179.93663]
 [200.06772]
 [138.07436]]
60 Cost:  6.6398606 
Prediction:
 [[150.95345]
 [184.5625 ]
 [179.93565]
 [200.0659 ]
 [138.07866]]
70 Cost:  6.6312766 
Prediction:
 [[150.94984]
 [184.56505]
 [179.93468]
 [200.06409]
 [138.08295]]
80 Cost:  6.622693 
Prediction:
 [[150.94627]
 [184.56763]
 [179.93375]
 [200.0623 ]
 [138.08727]]
90 Cost:  6.614187 
Prediction:
 [[150.94269]
 [184.57016]
 [179.93277]
 [200.06049]
 [138.09152]]
10