In [0]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
#버전 2.0으로 업그레이드됨에 따라 v1과 호환이 되지 않음

In [108]:
from google.colab import files
upload = files.upload()

Saving data-01-test-score.csv to data-01-test-score.csv


In [0]:
import numpy as np

In [110]:
xy = np.loadtxt('data-01-test-score.csv',delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]  # 전체 행을 다 가져오고 0부터 마지막꺼 하나 제외하고 불러옴
y_data = xy[:, [-1]] # 전체 행을 다 가져오고 마지막 하나만 가져오겠다.

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [0]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
#                           3개가 x가 들어와서 한개의 y값이 나간다.
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
#                               y 하나
# Hypothesis
hypothesis = tf.matmul(X, W) + b


In [0]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [0]:
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) # 0.0001
train = optimizer.minimize(cost)

In [111]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [177.17561]
 [167.24529]
 [144.01978]
 [190.83478]]
160 Cost:  17.699373 
Prediction:
 [[149.18704]
 [186.45914]
 [179.84062]
 [198.6736 ]
 [141.58382]
 [109.40805]
 [150.77425]
 [114.47913]
 [179.276  ]
 [172.80786]
 [144.50307]
 [146.66753]
 [183.08778]
 [148.63599]
 [152.83394]
 [191.21492]
 [140.3575 ]
 [181.13289]
 [172.99896]
 [154.49388]
 [176.89517]
 [177.16393]
 [167.24583]
 [144.05095]
 [190.83463]]
170 Cost:  17.597088 
Prediction:
 [[149.20284 ]
 [186.45197 ]
 [179.84758 ]
 [198.67445 ]
 [141.5774  ]
 [109.389854]
 [150.7722  ]
 [114.47462 ]
 [179.25497 ]
 [172.77115 ]
 [144.5002  ]
 [146.65057 ]
 [183.10141 ]
 [148.6552  ]
 [152.82721 ]
 [191.20364 ]
 [140.37587 ]
 [181.13223 ]
 [173.01706 ]
 [154.51169 ]
 [176.89142 ]
 [177.15228 ]
 [167.24638 ]
 [144.08199 ]
 [190.83446 ]]
180 Cost:  17.495722 
Prediction:
 [[149.21855]
 [186.44481]
 [179.8545 ]
 [198.67528]
 [141.571  ]
 [109.37173]
 [150.77014]
 [114.47013]
 [179.23404]
 [172.73459]

In [112]:
#학습된 모델을 바탕으로
#Ask my score
print("I :", sess.run(hypothesis, feed_dict={X: [[100,70,101]]}))
print("Other", sess.run(hypothesis, feed_dict={X: [[60,70,110], [90,100,80]]}))

I : [[194.0987]]
Other [[189.44936]
 [170.34793]]
